'Week 01':
  - 'Week 01/**/*'
'Week 02':
  - 'Week 02/**/*'
'Week 03':
  - 'Week 03/**/*'
'Week 04':
  - 'Week 04/**/*'
'Week 05':
  - 'Week 05/**/*'
'Week 06':
  - 'Week 06/**/*'
'Week 07':
  - 'Week 07/**/*'
'Week 08':
  - 'Week 08/**/*'
'Week 09':
  - 'Week 09/**/*'
'Week 10':
  - 'Week 10/**/*'
'Week 11':
  - 'Week 11/**/*'
'Week 12':
  - 'Week 12/**/*'
'Week 13':
  - 'Week 13/**/*'
'Week 14':
  - 'Week 14/**/*'
'Week 15':
  - 'Week 15/**/*'
'Week 16':
  - 'Week 16/**/*'
'Week 17':
  - 'Week 17/**/*'
'Week 18':
  - 'Week 18/**/*'
'Week 19':
  - 'Week 19/**/*'
'Week 20':
  - 'Week 20/**/*'
'Week 21':
  - 'Week 21/**/*'
'Week 22':
  - 'Week 22/**/*'
'Week 23':
  - 'Week 23/**/*'
'Week 24':
  - 'Week 24/**/*'
'Week 25':
  - 'Week 25/**/*'
'Week 26':
  - 'Week 26/**/*'
'Week 27':
  - 'Week 27/**/*'

'Assignment':
  - 'Week */submissions/**/*'

'cohort-1':
  - 'Week */submissions/cohort-1/**/*'

'cohort-2':
  - 'Week */submissions/cohort-2/**/*'

'Enhancement':
  - '*'
  - 'Week */**/*'
  - '!Week */submissions/**/*'
